import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import Game from '../components/Game'

const Title = styled.h1`
  max-width: 256px;
  font-size: 2em;
  margin: 0 auto;
  color: #333;
  text-align: center;
`

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dodle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Title>Dodle</Title>
      </header>
      <main>
        <Game />
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Home
