import type { NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import useSWR from 'swr';
import Modal from '../components/page/GameModal'
import Game from "../components/game/Game";
import Header from "../components/page/Header";
import { GameData } from "models/game_manager";
import { fetcher } from "lib/fetcher";
import styled from "styled-components";
import CompletedBoardRow from "components/game/GuessBoard/CompletedBoardRow";
import EmptyBoardRow from "components/game/GuessBoard/EmptyBoardRow";
import { LetterStatus } from "models/game";
import { useLocalStorage } from "lib/useLocalStorage";
import { ModalHeader } from "components/atoms/headings";
import { ExampleBoard } from "components/game/GuessBoard/ExampleBoard";
import GameLoadingScreen from "components/game/LoadingGame";
import ExternalLink from "components/atoms/ExternalLink";


const HelpSection = styled.section`
    max-width: 512px;
`



const Help: NextPage = () => {
    const { data, error } = useSWR<GameData>('/api/game', fetcher);
    const router = useRouter();

    const [allowTracking, setAllowTracking] = useLocalStorage<boolean>("event_tracking", true);

    return (
        <div>
            <Head>
                <title>dodle help</title>
                <meta name="description" content="How to play the dodle guessing game." />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main>
                <Modal isOpen={true} onClose={() => router.push("/")}>
                    <ModalHeader>What is this game?</ModalHeader>
                    <HelpSection>
                        <p>
                            Dodle is&nbsp;
                            <ExternalLink
                                href="https://www.nytimes.com/games/wordle/index.html"
                            >
                                Wordle
                            </ExternalLink>
                            &nbsp;inspired game based, on the open source&nbsp; 
                            <a 
                                href="https://github.com/borisdayma/dalle-mini"
                                target="_blank"
                                rel="nofollow">dalle mini</a>
                            &nbsp;deep learning model.<br/>
                            Images are generated by the model on a regular basis, based on a curated
                            randomized list of words that is combined to a prompt. Each day one of 
                            the images is presented.
                            <br/>
                            The goal of the game is to try to guess what an A.I. tried to draw.
                            With each guess you get a new image, that represents the <b>same</b>
                            &nbsp;word. Each new image <i>should</i> be better then the
                            previous one and thus theoretically make it clearer what the word
                            to guess is.<br />
                            Unfortunately the A.I. is sometimes kind of a abstract artist and thus
                            a new image might not make clearer it 😄.
                        </p>
                        <div>
                            The game tracks the following <b>anonymous</b> stats in order to improve it:
                            <ul>
                                <li>If was completed and if it was successful</li>
                                <li>Stats from the stats page</li>
                                <li>The entered guesses per game</li>
                            </ul>
                            No private or identifiable data is tracked.
                        </div>
                        <form>
                            <input
                                type="checkbox"
                                id="tracking"
                                name="tracking"
                                checked={allowTracking}
                                onChange={(e) => setAllowTracking(e.target.checked)}
                            />
                            <label htmlFor="tracking">
                                Allow to track guesses to improve the game.
                            </label>
                        </form>
                        <hr/>
                        <p>
                            Created by&nbsp;
                            <a href="https://twitter.com/sepgil" 
                            target="_blank" rel="noreferrer">@sepgil</a><br/>
                            Code can be found on&nbsp;
                            <a href="https://github.com/sepal/dodle"
                            target="_blank" rel="noreferrer">github/sepal/dodle</a>
                        </p>

                    </HelpSection>
                </Modal>

                {error && "Sorry, couldn't load game."}
                {data && <GameLoadingScreen />}
            </main>
        </div>
    );
}

export default Help;